version: '3.7'

services:
  db:
    image: mysql:8.0.19
    container_name: mysql-golab
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "golab"
      MYSQL_DATABASE: golab
      MYSQL_USER: golab
      MYSQL_PASSWORD: golab

  redis:
    image: redis:5.0.8
    container_name: redis-golab
    hostname: redis
    command: redis-server --appendonly yes --requirepass golab
    restart: always
    ports:
      - "16379:6379"

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq-stream
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "golab"
      RABBITMQ_DEFAULT_PASS: "golab"