
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/golab?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: golab
    password: golab
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        user_sql_comments: true

redis:
  host: localhost
  port: 16379
  password: golab

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

vc:
  upbit:
    base_url: https://api.upbit.com/v1
  bithumb:
    base_url: https://api.bithumb.com