
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/golab?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: golab
    password: golab
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  redis:
    host: localhost
    port: 6379